[package]
name = "horatio"
version = "0.1.0"
authors = ["Philip Cunningham <hello@filib.io>"]

[dependencies]
chrono = { version = "~0.4.0", features = ["serde"] }
reqwest = "~0.8.0"
serde = "~1.0"
serde_derive = "~1.0"
serde_json = "~1.0"